### ISSUE TITLE
Restore Aero Glass support

### ISSUE THREAD

**Issue by Infocatcher** [gomita/tabscope#45]
Also suggested here: https://addons.mozilla.org/addon/tab-scope/reviews/user:1735045
And here: https://addons.mozilla.org/addon/tab-scope/reviews/493762/

I think, extension should use system or browser appearance (if possible, of course).

Let's see.
This is Windows 7 with Tab Scope 1.2:
![Screenshot: Windows 7 + Tab Scope 1.2](https://f.cloud.github.com/assets/601488/897785/8fdb3f68-faf9-11e2-9270-3c18006b7db2.png)
Style of Tab Scope's popup/panel is very similar to window style.

And now Windows 7 with Tab Scope 1.3.3:
![Screenshot: Windows 7 + Tab Scope 1.3.3](https://f.cloud.github.com/assets/601488/897796/c83d31d6-faf9-11e2-8448-d040f289edc6.png)
May be good on Windows 8, but looks a bit "not from here" on Windows 7.

Also I tried to write style for userChrome.css, but unfortunately still see strange glitch on bottom-right corner:
![Screenshot: Windows 7 + Tab Scope 1.3.3 + custom CSS](https://f.cloud.github.com/assets/601488/897815/8473b1fe-fafa-11e2-8728-c27e6f296954.png)
Style:

``` css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@-moz-document url("chrome://browser/content/browser.xul") {
    /* Aero glass for Tab Scope 1.3.3+, based on styles from Tab Scope 1.2 */
    #tabscope-popup:-moz-system-metric(windows-compositor) {
        background: transparent !important;
        -moz-appearance: -moz-win-glass !important;
        box-shadow: none !important;
        border: none !important;
        border-radius: 0 !important;
        color: black !important;
        text-shadow: white -1px -1px .5em, white -1px 1px .5em, white 1px 1px .5em, white 1px -1px .5em !important;
    }
    #tabscope-container:-moz-system-metric(windows-compositor) {
        margin: 1px !important;
        background: transparent !important;
        -moz-appearance: none !important;
        box-shadow: none !important;
        border: none !important;
        border-radius: 0 !important;
    }
}
```

So, I propose to restore glass for Windows 7 and leave new flat style for Windows 8.
